.KEEP_STATE:
include ../../etc/make/header.make

PKG_NAME = libutil
PKG_DEPS = 

UTIL_HEAD = header.h

UTIL_INCS =     \
		link.h \
		list.h \
		hash.h \
		array.h \
		farray.h \
		sort.h \
		str.h \
		file.h \
		status.h \
		iofunc.h 

UTIL_OBJS =     \
		link.o \
		list.o \
		hash.o \
		array.o \
		farray.o \
		sort.o \
		str.o \
		file.o \
		status.o \
		iofunc.o

include ../../etc/make/liba.make
