include ../../etc/make/header.make

PKG_NAME = libgds
PKG_DEPS = libutil

UTIL_HEAD = header.h
UTIL_INCS = gdsdata.h gdsutil.h gdsfilter.h gdsmain.h
UTIL_OBJS = gdsdata.o gdsutil.o gdsfilter.o gdsmain.o

include ../../etc/make/liba.make
